import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/UI/NavBar";
import "bootstrap/dist/css/bootstrap.css";
import ApplicationContextProvider from "@/context/ApplicationContextProvider";
import MyModal from "@/components/UI/MyModal";
import AuthProvider from "@/context/AuthProvider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <ApplicationContextProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <NavBar />
            {children}
            <MyModal />
          </body>
        </ApplicationContextProvider>
      </AuthProvider>
    </html>
  );
}
